### PR TITLE
reorganized routing system and deleted unnecessary files

### PR DESCRIPTION
**Pull request by stevenshuhyow**
Reorganized the routing system.
Each type of request has it's own file.
Deleted unnecessary files.

### CODE REVIEW

**Comment by kurtbartholomew** [comment]
Why is sequelize declared twice in the db/index.js file? (once as orm and once as Sequelize)

**Comment by stevenshuhyow** [comment]
oh that happened because i merged the changes that vivek made and forgot to delete the one I added in as well.

**Comment by kurtbartholomew** [comment]
:+1:

**Comment by mwbennett** [comment]
:+1:

**Pull request merged**
