### PR TITLE
(feat) added proposed ui-router structure for front-end views

### PR DESCRIPTION
**Pull request by mwbennett**
NOTE: ONLY PARTIALLY COMPLETE 
- The proposed view structure in `public/app/app.module.js` references templates, controllers, and modules that don't yet exist. I wanted to let you guys review the proposed structure before I move forward with drastically adding to the file structure. 
- I used https://scotch.io/tutorials/angular-routing-using-ui-router along with our shortly-angular codebase as guides 
- forgot to mention explicitly in the comments : proposed home state would be for authenticated users only, as we've discussed previously

### CODE REVIEW

**Comment by vtumrukota** [comment]
Looks good Mark

**Comment by kurtbartholomew** [comment]
Wait, where is the root url view? I see handling of 3 different routes, but no '/' route handling. Did I miss it?

**Comment by kurtbartholomew** [comment]
Get back to me when you can, for now I'm going to merge it in since it is a purely front end thing.

**Comment by mwbennett** [comment]
Kurt - I was treating the 'home' view as synonymous with the root view. My understanding was that if you navigated to the root, the `otherwise` statement on line 12 would redirect to the home path. If that's non-standard, I'm happy to change the url for the home state to the root, and then update the `otherwise` statement. Let me know what you think.

**Pull request merged**
