### PR TITLE
(Feat) routes

### PR DESCRIPTION
**Pull request by stevenshuhyow**
Issue #14 

Router now able to route to specific controller for get and post requests.
Need to still work on controller to respond to the router

### CODE REVIEW

**Comment by kurtbartholomew** [comment]
Looks good :+1:

**Comment by vtumrukota** [comment]
:+1:

**Comment by mwbennett** [comment]
A couple questions on this one: 
- Do we need the schema in raw SQL since we're using Sequelize? Doesn't sequelize create the schema for us under the hood? 
- probably not a big priority, but should we be handling for errors on our post and get requests?

**Comment by stevenshuhyow** [comment]
Nope we don't need the raw SQL.  I just wanted to put it inside to help me create the DB file.
Also, if you look in the DB file, I am handling the errors inside of there.  Let me know if you have questions about anything else

**Comment by mwbennett** [comment]
Got it. Awesome, thanks for clarifying. Looking good! :+1:

**Pull request merged**
